### PR TITLE
Pin module version

### PR DESCRIPTION
**Pull request by RothAndrew**
We should always be using pinned versions.

### CODE REVIEW

**Review by zachariahmiller — APPROVED** [review]
LGTM

**Review by zachariahmiller — COMMENTED** [review]
i agree with being explicit with the version but is there a reason we are downgrading that version?

**Comment by RothAndrew** [comment]
Something got screwed up with this PR. Gonna close this one and reopen

**Comment by RothAndrew** [comment]
#11

**Pull request closed without merging**
